version: '3.8'

services:
  app:
    build: .
    container_name: datamatrix_decoder_app_rtsp
    volumes:
      - ${RESULTS_DIR}:/app/results
    environment:
      - URL=${URL}
      - TIMEOUT=${TIMEOUT}
      - EXPECTED_NUM=${EXPECTED_NUM}
      - LOG_LEVEL=${LOG_LEVEL}
      - HTTP_PORT=${HTTP_PORT}
      - RESULTS_DIR=${RESULTS_DIR}
      - MAX_FAILED_ATTEMPTS=${MAX_FAILED_ATTEMPTS}
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
#    network_mode: "host"
    command: >
      python app.py
      --url ${URL}
      --timeout ${TIMEOUT}
      --expected_num ${EXPECTED_NUM}
      --log_level ${LOG_LEVEL}
      --http_port ${HTTP_PORT}
      --max_failed_attempts ${MAX_FAILED_ATTEMPTS}
#      --test
